### ISSUE TITLE
Issue with "-" syntax for dependent variables

### ISSUE THREAD

**Issue by JacobHerbstman** [droodman/reghdfejl#3]
I am running an event study regression. We have many lag and lead indicators and want to express them as lag_1-lag_10, for example. Stata has been crashing when running this specification (which works with regular reghdfe) and does not crash when we write out lag_1, lag_2, lag_3, ... lag_10 individually. However, we need the original notation because the number of lags is dynamic, and it appears that formulation crashes reghdfejl.

**Comment by droodman** [comment]
Fixed with v0.4.1 (I hope).

**Comment by JacobHerbstman** [comment]
This is working! Thank you so much.
