### ISSUE TITLE
Issue with Bootstrap

### ISSUE THREAD

**Issue by xinweiwan** [droodman/reghdfejl#6]
Hi,

My Windows machine can run reghdfejl successfully once. However, when I was trying to combine Bootstrap with reghdfejl, it ends up with an error of updating the temp files.

bootstrap, reps(100) seed(1): reghdfejl ln_wage grade age ttl_exp tenure not_smsa south, absorb(idcode year)

file C:\StataTemp\xxx.tmp cannot be modified or erased; likely cause is read-only directory or file
r(608);

This issue exits on multiple Windows machines that I have tested. Changing the directory of temp files will not resolve the issue. Also, running Bootstrap with the original reghdfe comment works. 

Thank you!

**Comment by droodman** [comment]
I will look at it. But why don't you use the vce(bs...) option instead? It is much faster (though slow on the first use). There is an example in the help file.

**Comment by xinweiwan** [comment]
I was not aware of the new option you provided. Yes, that should solve the
problem. Many thanks!

Regards,
Wayne Xinwei Wan

**Comment by xinweiwan** [comment]
Hi,

Sorry for troubling you again. I think the issue comes from the
post-regression analysis after the first run of the command. Your new
option resolves the iterations in the original bootstrap command, but the
issue persists if some other post-regression analysis is required.

Take the simple outreg2 as an example. If run the following code together:
webuse nlswork
reghdfejl ln_wage age ttl_exp tenure not_smsa south, absorb(year occ_code)
vce(bs, cluster(occ_code) reps(1000) seed(42) procs(4))
outreg2 using F:\test.xls,  bdec(4) sdec(4) append addstat(Mean, e(ymean))
label adec(3)

Error message:
file F:\StataTemp\ST_4e34_000002.tmp cannot be modified or erased; likely
cause is read-only directory or file
nothing to restore
could not restore sort order because variables were dropped

**Comment by droodman** [comment]
That is working for me in Windows, at least once I drop the addstat() and adec() options:

```
. reghdfejl ln_wage age ttl_exp tenure not_smsa south, absorb(year occ_code) vce(bs, cluster(occ_code) reps(1000) seed(42) procs(4))
(MWFE estimator converged in 6 iterations)

HDFE linear regression with Julia                 Number of obs   =     27,973
Absorbing 2 HDFE groups                           F(   5,     13) =     542.80
Statistics cluster-robust                         Prob > F        =     0.0000
                                                  R-squared       =     0.4105
                                                  Adj R-squared   =     0.4098
                                                  Within R-sq.    =     0.1650
                                                  Root MSE        =     0.3671

                               (Replications based on 13 clusters in occ_code)
------------------------------------------------------------------------------
             |   Observed   Bootstrap                         Normal-based
     ln_wage | coefficient  std. err.      t    P>|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
         age |   .0042979   .0011326     3.79   0.002      .001851    .0067448
     ttl_exp |   .0308828   .0029162    10.59   0.000     .0245826    .0371829
      tenure |   .0157172    .001835     8.57   0.000     .0117529    .0196814
    not_smsa |  -.1615383   .0153971   -10.49   0.000    -.1948018   -.1282748
       south |  -.1210285   .0204315    -5.92   0.000    -.1651681   -.0768889
------------------------------------------------------------------------------

. outreg2 using test.xls,  bdec(4) sdec(4) append addstat(Mean, e(ymean)) label adec(3)
check eret list for the existence of e(ymean)
c:\ado\plus/o/outreg2.ado
test.xls
dir : seeout

. outreg2 using test.xls,  bdec(4) sdec(4) append label
test.xls
dir : seeout

. 
```

If you want, you can do `set trace on` and send me the log file.

**Comment by droodman** [comment]
The earlier `bootstrap` command also works for me. Here too, you can send me the trace log:
```
. bootstrap, reps(100) seed(1): reghdfejl ln_wage grade age ttl_exp tenure not_smsa south, absorb(idcode year)
(running reghdfejl on estimation sample)

Bootstrap replications (100): .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100 done
(dropped 550 singleton observations)
(MWFE estimator converged in 12 iterations)

HDFE linear regression with Julia                 Number of obs   =     27,541
Absorbing 2 HDFE groups                           F(   5,      .) =          .
                                                  Prob > F        =          .
                                                  R-squared       =     0.6762
                                                  Adj R-squared   =     0.6185
                                                  Within R-sq.    =     0.0531
                                                  Root MSE        =     0.2939

------------------------------------------------------------------------------
             |   Observed   Bootstrap                         Normal-based
     ln_wage | coefficient  std. err.      z    P>|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
       grade |          0  (omitted)
         age |   .0114497   .0112983     1.01   0.311    -.0106945     .033594
     ttl_exp |   .0323758   .0018779    17.24   0.000     .0286952    .0360563
      tenure |   .0104689   .0010556     9.92   0.000        .0084    .0125378
    not_smsa |  -.0914148   .0120741    -7.57   0.000    -.1150796   -.0677501
       south |  -.0640471   .0117199    -5.46   0.000    -.0870177   -.0410764
------------------------------------------------------------------------------


```

**Comment by xinweiwan** [comment]
Here is the log file from my machine. Thank you very much!

**Comment by droodman** [comment]
Also, make sure you have the latest `reghdfejl` and `jl` with:
```
ssc install reghdfejl, replace
ssc install julia, replace
```

**Comment by droodman** [comment]
It looks like the log file won't come through that way. My email address is in the help file.

**Comment by droodman** [comment]
Well the error is coming from `outreg2` when it tries to `preserve` the data. So I don't think it's really a `reghdfejl` issue. See https://www.statalist.org/forums/forum/general-stata-discussion/general/1405940-file-cannot-be-modified-or-erased-likely-cause-is-read-only-directory-or-file. You can also try contacting the author of `outreg2`.
